# Generated by Django 3.2.12 on 2022-03-05 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='dist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.profession')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=13)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('password', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('dist_name', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App1.dist')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('profession', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App1.profession')),
                ('state_name', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App1.state')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('remark', models.CharField(default=True, max_length=500)),
                ('date_and_time', models.DateTimeField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('dist_name', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App1.dist')),
                ('profession', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App1.profession')),
                ('specialist', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('state_name', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App1.state')),
            ],
        ),
        migrations.AddField(
            model_name='dist',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.profession'),
        ),
        migrations.AddField(
            model_name='dist',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.state'),
        ),
    ]
